name: document
on:
  push:
    branches:
      - master
      - dev
jobs:
  asciidoc:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor
    steps:
      - uses: actions/checkout@v2
      - name: build html
        run: asciidoctor -o target/html/index.html doc/pages/index.adoc
      - uses: actions/upload-artifact@master
        with:
          name: asciidoc_index.html
          path: target/html/index.html

  help:
    needs: asciidoc
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-14-tools-deps
    steps:
      - uses: actions/checkout@v2
      - name: Cache m2
        uses: actions/cache@v1.1.0
        with:
          path: /root/.m2
          key: document-root-m2-${{ hashFiles('deps.edn') }}
      - name: build help html
        run: bash scripts/html.sh
      - uses: actions/download-artifact@master
        with:
          name: asciidoc_index.html
          path: tmp/html
      - name: copy index.html
        run: cp -pf tmp/html/index.html target/html/index.html
      - name: copy assets
        run: cp -pr doc/pages/assets target/html/assets
      - uses: actions/upload-artifact@master
        with:
          name: document
          path: target/html

  nightly-deploy:
    if: github.ref == 'refs/heads/dev'
    needs: [asciidoc, help]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: document
          path: document
      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PERSONAL_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=document --prod

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [asciidoc, help]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: document
          path: document
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./document
