name: lint
on: [push, pull_request]
jobs:
  vint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install -r requirements.txt
      - run: bash scripts/lint.sh

  clj-kondo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # c.f. https://github.com/borkdude/clj-kondo/blob/master/doc/ci-integration.md#linter-output-integration
      - name: Lint by clj-kondo
        run: docker run --rm -v $(pwd):/tmp/work -w /tmp/work borkdude/clj-kondo clj-kondo --lint clj:test/clj --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
